# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: justin leatherwood
email: jplwood@gmail.com
description: > # Justin Leatherwood's personal site/blog thingee.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://justinleatherwood.com" # the base hostname & protocol for your site
twitter_username: jplwood
github_username:  jplwood


# Build settings
permalink:   pretty
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      excerpt_separator: "<!--more-->"
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "general"

sass:
  style: compressed
